export const regions = [
    {  name: 'Central', value: 'Central', capital: 'Cape Coast', districts: ['Abura/Asebu/Kwamankese', 'Agona East', 'Agona West', 'Ajumako/Enyan/Essiam', 'Asikuma/Odoben/Brakwa', 'Assin North', 'Assin South', 'Awutu-Senya', 'Cape Coast', 'Effutu', 'Ekumfi', 'Gomoa East', 'Gomoa West', 'Komenda/Edina/Eguafo/Abirem', 'Mfantsiman', 'Twifo-Ati Morkwa', 'Upper Denkyira East', 'Upper Denkyira West']},
    {  name: 'Brong-Ahafo', value: 'Brong-Ahafo', capital: 'Sunyani', districts: ['Asunafo North', 'Asunafo South', 'Asutifi North', 'Asutifi South', 'Atebubu-Amantin', 'Berekum', 'Dormaa East', 'Dormaa West', 'Jaman North', 'Jaman South', 'Kintampo North', 'Kintampo South', 'Nkoranza North', 'Nkoranza South', 'Pru', 'Sene', 'Sunyani', 'Tain', 'Tano North', 'Tano South', 'Techiman', 'Wenchi']},
    {  name: 'Eastern', value: 'Eastern', capital: 'Koforidua', districts: ['Akuapim North', 'Akuapim South', 'Akyemansa', 'Asuogyaman', 'Atiwa', 'Ayensuano', 'Birim Central', 'Birim North', 'Birim South', 'Denkyembour', 'Fanteakwa', 'Kwaebibirem', 'Kwahu East', 'Kwahu South', 'Kwahu West', 'Lower Manya Krobo', 'New Juaben North', 'New Juaben South', 'Suhum/Kraboa/Coaltar', 'Upper Manya Krobo', 'West Akim', 'Yilo Krobo']},
    {  name: 'Northern', value: 'Northern' , capital: 'Tamale', districts: ['Bole', 'Bunkpurugu-Yunyoo', 'Central Gonja', 'Chereponi', 'East Gonja', 'East Mamprusi', 'Gushiegu', 'Karaga', 'Kpandai', 'Kumbungu', 'Mamprugu Moagduri', 'Mion', 'Nanumba North', 'Nanumba South', 'North Gonja', 'Saboba', 'Sagnarigu', 'Savelugu-Nanton', 'Sawla-Tuna-Kalba', 'Tamale', 'Tatale-Sanguli', 'Tolon', 'West Gonja', 'West Mamprusi', 'Yendi', 'Zabzugu', 'Zabzugu-Tatale']},
    {  name: 'Western', value: 'Western',  capital: 'Sekondi-Takoradi', districts: ['Ahanta West', 'Aowin/Suaman', 'Bia', 'Bibiani/Anhwiaso/Bekwai', 'Ellembelle', 'Jomoro', 'Juabeso', 'Mpohor/Wassa East', 'Nzema East', 'Prestea-Huni Valley', 'Sefwi Akontombra', 'Sefwi Wiawso', 'Sekondi Takoradi', 'Shama', 'Tarkwa-Nsuaem', 'Wassa Amenfi Central', 'Wassa Amenfi East', 'Wassa Amenfi West']},
    {  name: 'Upper East', value: 'Upper East', capital: 'Bolgatanga', districts: ['Bawku Municipal', 'Bawku West', 'Bolgatanga Municipal', 'Bongo', 'Builsa', 'Builsa South', 'Garu-Tempane', 'Kassena/Nankana East', 'Kassena/Nankana West', 'Nabdam', 'Pusiga', 'Talensi', 'Tempane']},
    {  name: 'Upper West', value: 'Upper West', capital: 'Wa', districts: ['Daffiama-Bussie-Issa', 'Jirapa', 'Lambussie Karni', 'Lawra', 'Nadowli', 'Nandom', 'Sissala East', 'Sissala West', 'Wa East', 'Wa West']},
    {  name: 'Volta', value: 'Volta', capital: 'Ho', districts: ['Adaklu', 'Afadzato South', 'Agotime Ziope', 'Akatsi North', 'Akatsi South', 'Biakoye', 'Central Tongu', 'Ho', 'Ho West', 'Hohoe', 'Jasikan', 'Kadjebi', 'Keta', 'Ketu North', 'Ketu South', 'Kpando', 'Krachi East', 'Krachi Nchumuru', 'Krachi West', 'Nkwanta North', 'Nkwanta South', 'North Dayi', 'North Tongu', 'South Dayi', 'South Tongu']},
    {  name: 'Ashanti', value: 'Ashanti', capital: 'Kumasi', districts: ['Adansi North', 'Adansi South', 'Afigya-Kwabre', 'Ahafo Ano North', 'Ahafo Ano South', 'Amansie Central', 'Amansie West', 'Asante Akim Central', 'Asante Akim North', 'Asante Akim South', 'Asokore Mampong', 'Atwima Kwanwoma', 'Atwima Mponua', 'Atwima Nwabiagya', 'Bekwai Municipal', 'Bosome Freho', 'Bosomtwe', 'Ejisu-Juaben', 'Ejura/Sekyedumase', 'Kumasi Metropolitan', 'Kwabre East', 'Mampong Municipal', 'Obuasi Municipal', 'Obuasi East', 'Offinso North', 'Offinso South', 'Sekyere Afram Plains', 'Sekyere Central', 'Sekyere East', 'Sekyere South', 'Sekyere West', 'Subin', 'Suame', 'Tano North', 'Tano South']},
    {  name: 'Greater Accra', value: 'Greater Accra', capital: 'Accra', districts: ['Accra Metropolitan', 'Ada East', 'Ada West', 'Adenta', 'Ashaiman', 'Dangme East', 'Dangme West', 'Ga Central', 'Ga East', 'Ga South', 'Ga West', 'Kpone Katamanso', 'Ledzokuku-Krowor', 'Ningo Prampram', 'Shai Osudoku', 'Tema Metropolitan', 'Tema West']},
    {  name: 'Western North', value: 'Western North', capital: 'Sefwi Wiawso', districts: ['Aowin/Suaman', 'Bia', 'Bibiani/Anhwiaso/Bekwai', 'Juabeso', 'Sefwi Akontombra', 'Sefwi Wiawso']},
    {  name: 'Oti', value: 'Oti', capital: 'Dambai', districts: ['Biakoye', 'Jasikan', 'Kadjebi', 'Krachi East', 'Krachi Nchumuru', 'Krachi West', 'Nkwanta North', 'Nkwanta South']},
    {  name: 'Ahafo', value: 'Ahafo', capital: 'Goaso',districts: ['Asutifi North', 'Asutifi South', 'Tano North', 'Tano South']},
    {  name: 'Bono East', value: 'Bono East', capital: 'Techiman', districts: ['Atebubu-Amantin', 'Kintampo North', 'Kintampo South', 'Nkoranza North', 'Nkoranza South', 'Pru', 'Sene', 'Techiman']},
    {  name: 'Savannah', value: 'Savannah', capital: 'Damongo', districts: ['Bole', 'Central Gonja', 'North Gonja', 'Sawla-Tuna-Kalba']},
    {  name: 'North East', value: 'North East', capital: 'Nalerigu', districts: ['Bunkpurugu-Yunyoo', 'East Mamprusi', 'Gushiegu', 'Karaga', 'Kassena/Nankana West', 'Nanumba North', 'Nanumba South', 'Saboba', 'Talensi', 'West Mamprusi', 'Yendi', 'Zabzugu', 'Zabzugu-Tatale']}
];
